### ISSUE TITLE
Rewrite Component Generator

### ISSUE THREAD

**Issue by bearded-avenger** [hyunsupul/aesop-core#54]
The current rendition of the generator is great, but needs to be rewritten to include the ability to edit components. Having to manually edit them, or recreate them is a pain in the nuts.

**Ideal user flow**
1. User clicks "add component" button like current
2. Modal pops up, presents them with components area 
3. User operates largely as they do now
4. Components then appear as a graphic, with edit icon
5. User clicks edit icon and is shown only that components attributes to edit and save

**Todo**
- [x] create mockup of new generator

**Must have**
- [x] media library integration
- [x] colorpicker (keep old or go with new iris?)
- [x] filterable tabbed area for 3rd party plugins to hook into 
- [x] components modal area must be filterable
